### ISSUE TITLE
No support Multiple custom images??   Consider increasing a field of CRD:   `image`

### ISSUE THREAD

**Issue by nicole-lihui** [cloudtty/cloudtty#124]
only found one method to define custom image config, and then no supported multiple custom images
```
helm install cloudtty-operator --version 0.3.0 daocloud/cloudtty --set jobTemplate.image.registry=</REGISTRY> --set jobTemplate.image.repository=</REPOSITORY> --set jobTemplate.image.tag=</TAG>
```

Suggestion：  in CloudShell CRD add  a field ：`image`
```bash
spec:
  image: 
      registry: test.io
      repository:  custom-image
      tag: v1.0.0
```

**Comment by calvin0327** [comment]
@nicole-lihui thanks, do you think it's better if we set a field to represent image, like this:

```yaml
spec:
  image: test.io/custom-image:v1.0.0
```

**Comment by nicole-lihui** [comment]
> @nicole-lihui thanks, do you think it's better if we set a field to represent image, like this:
> 
> ```yaml
> spec:
>   image: test.io/custom-image:v1.0.0
> ```

This is a good idea
