### ISSUE TITLE
The configmap of kube.conf is optional

### ISSUE THREAD

**Issue by panpan0000** [cloudtty/cloudtty#14]
When cloudtty managers the same local cluster where it resists, the kube.conf configmap prerequisite may not be necessary, cloudtty pod can leverage default or specific SA token .

Sub Task:
1. Necessary/Full SA privilege should be granted
2. CR definition polish
3. Use `/var/run/secrets/kubernetes.io/serviceaccount` in pod, and k8s endpoint from `ENV`

@calvin0327

**Comment by calvin0327** [comment]
ok, I will solve the issue.

/assign
