### ISSUE TITLE
helm 安装错误 提示 Error: INSTALLATION FAILED: failed to download "cloudtty/cloudtty" at version "0.5.0"

### ISSUE THREAD

**Issue by hootinwang** [cloudtty/cloudtty#199]

**Comment by calvin0327** [comment]
可以提供下安装的方式，是直接使用 helm 命令进行安装的吗？

**Comment by hootinwang** [comment]
> 可以提供下安装的方式，是直接使用 helm 命令进行安装的吗？

对，按照文档安装的，对k8s版本有要求吗

**Comment by calvin0327** [comment]
helm repo add cloudtty https://release.daocloud.io/chartrepo/cloudshell
@hootinwang readme 有点小问题，需要修改成 
helm repo add cloudtty https://release.daocloud.io/chartrepo/cloudtty

**Comment by calvin0327** [comment]
我们将会更新 readme。抱歉

**Comment by calvin0327** [comment]
@hootinwang 我们已经更新了文档，你可以再跟着文档试试。

**Comment by hootinwang** [comment]
@calvin0327 可以把我拉倒微信讨论群吗

**Comment by calvin0327** [comment]
@hootinwang 可以的，可以私信发我微信号
