### ISSUE TITLE
ingressConfig host

### ISSUE THREAD

**Issue by clcc2019** [cloudtty/cloudtty#216]
<img width="484" alt="image" src="https://user-images.githubusercontent.com/46099295/216247386-79c3c746-18e9-4ac4-9b00-a8551eb92f46.png">
<img width="417" alt="image" src="https://user-images.githubusercontent.com/46099295/216247554-d410e9ca-7022-426b-bf85-307062ccf1d9.png">

Hope to support configuration host

**Comment by calvin0327** [comment]
@clcc2019 thanks your feedback, we will support the feature in the next release.
