### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by chaunceyjiang** [cloudtty/cloudtty#261]
![image](https://github.com/cloudtty/cloudtty/assets/17962021/eb7f0cbe-2393-40b6-b340-a9b5a4864b59)

version:

cloudtty/cloudshell-operator:v0.5.2

**Comment by calvin0327** [comment]
resolved by  https://github.com/cloudtty/cloudtty/pull/263
