### ISSUE TITLE
容器里df 命令无法查看到挂载信息

### ISSUE THREAD

**Issue by gssjl2008** [cloudtty/cloudtty#274]
<img width="606" alt="image" src="https://github.com/cloudtty/cloudtty/assets/43020699/a3a94c67-dc2e-432b-b232-f80f8690c60c">

信息如图，Global集群 部署2048 ，无其他操作

**Comment by calvin0327** [comment]
@gssjl2008 你现在 df 命名看到的信息并非目标容器的信息，而是 cloudtty 自己本身的容器的信息。

**Comment by gssjl2008** [comment]
奇怪的是，自身任何信息都没有吗？
