### ISSUE TITLE
Replace the daocloud helm repo with github helm repo or other

### ISSUE THREAD

**Issue by yankay** [cloudtty/cloudtty#28]
Daocloud helm repo is not neutrality.

![image](https://user-images.githubusercontent.com/1469319/173056318-e13c5887-d953-42f0-8a07-31d721ef5d52.png)

 Maybe Github helm repo(https://medium.com/@mattiaperi/create-a-public-helm-chart-repository-with-github-pages-49b180dbb417) is better.

**Comment by panpan0000** [comment]
still struggle with https://github.com/cloudtty/cloudtty/blob/main/.github/workflows/helm-release.yaml
ghcr.io does not officially support helm repo, but with gh-pages workaround, and gh-pages has not be enabled so far..
