### ISSUE TITLE
 there are Chinese hard code in this file, does Cloudtty support I18N?

### ISSUE THREAD

**Issue by liyuerich** [cloudtty/cloudtty#286]
https://github.com/cloudtty/cloudtty/blob/aa1c39ffd4d38500d55db6764831d5d79e1e301b/html/src/components/app.tsx#L 

 there are Chinese hard code in this file, does Cloudtty support I18N?

**Comment by calvin0327** [comment]
We seem to not support I18N.

@youhonglian

**Comment by youhonglian** [comment]
the current solution is to use English first instead of hard-coded Chinese
