### ISSUE TITLE
How to make this pod persistent, thank you.

### ISSUE THREAD

**Issue by wanminny** [cloudtty/cloudtty#290]

**Comment by wanminny** [comment]
+1

**Comment by wanminny** [comment]
local-cluster                 bash      NodePort   10.1.30.21:32517   Complete   29m

**Comment by wanminny** [comment]
> CloudShell

why use deploy to owner this cr . use job has some disadvantage

**Comment by wanminny** [comment]
> @wanminny you can set the ttl to `CloudShell` CR, this is lifetime of pod.

why not use deploy to owner this cr . use job has some disadvantage

**Comment by calvin0327** [comment]
@wanminny I'm curious are there any scenarios that require a permanent cloudshell?
