### ISSUE TITLE
 `GLIBC_2.32' not found 

### ISSUE THREAD

**Issue by liuzm617** [cloudtty/cloudtty#302]
docker run --rm ghcr.io/cloudtty/cloudshell-operator:latest manager --leader-elect-resource-namespace=default --v=2 

error:
manager: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by manager)
manager: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by manager)
换了好几个服务器尝试都是这样；每个服务器本机都有GLIBC_2.32和GLIBC_2.34的。

strings /lib/x86_64-linux-gnu/libc.so.6 |grep GLIBC_
GLIBC_2.2.5
GLIBC_2.2.6
GLIBC_2.3
GLIBC_2.3.2
GLIBC_2.3.3
GLIBC_2.3.4
GLIBC_2.4
GLIBC_2.5
GLIBC_2.6
GLIBC_2.7
GLIBC_2.8
GLIBC_2.9
GLIBC_2.10
GLIBC_2.11
GLIBC_2.12
GLIBC_2.13
GLIBC_2.14
GLIBC_2.15
GLIBC_2.16
GLIBC_2.17
GLIBC_2.18
GLIBC_2.22
GLIBC_2.23
GLIBC_2.24
GLIBC_2.25
GLIBC_2.26
GLIBC_2.27
GLIBC_2.28
GLIBC_2.29
GLIBC_2.30
GLIBC_2.31
GLIBC_2.32
GLIBC_2.33
GLIBC_2.34
GLIBC_2.35
GLIBC_PRIVATE

**Comment by liuzm617** [comment]
使用v0.5.0正常，v0.5.5就上面的问题

**Comment by calvin0327** [comment]
@liuzm617 感谢你的反馈，确实有这个问题。

**Comment by calvin0327** [comment]
@liuzm617 Operator 的镜像没有静态编译导致了这个问题，我们会发一个新的版本。
