### ISSUE TITLE
[BUG] If the file contains Chinese characters, it cannot be downloaded successfully.

### ISSUE THREAD

**Issue by CoderTH** [cloudtty/cloudtty#322]
Does not contain Chinese, downloaded successfully
![image](https://github.com/cloudtty/cloudtty/assets/51119718/f343856d-5ea2-49c5-9abe-591909151f6e)

Contains Chinese, download failed error 404
![image](https://github.com/cloudtty/cloudtty/assets/51119718/3e822b08-03c9-4347-bb4c-7066444a0f42)

**Comment by calvin0327** [comment]
@youhonglian /cc
