### ISSUE TITLE
ARM64 support

### ISSUE THREAD

**Issue by yankay** [cloudtty/cloudtty#41]
If we want to support ARM64, the image shoube be multi-arch

**Comment by lengrongfu** [comment]
I think it can support multi-architecture images, we can use `docker buildx` to build an image to support multiple architectures.

**Comment by barnettZQG** [comment]
I create a new project to build multiple platform images, including the ARM64. maybe you can refer to it.
https://github.com/kubevela/cloudshell

**Comment by panpan0000** [comment]
@barnettZQG 

(1) Use customized image
 The team had discussed about  the need of "customized runtime image" , because diff people want diff tools in image.
so @calvin0327 has introduced the capability .
When helm install cloudtty, add `--set jobTemplate.image.repository=kubevela/cloudshell ` to use your own image.
(2) Build your own image:
I take a quick look on your https://github.com/kubevela/cloudshell , I think can do it by 
```
 FROM ghcr.io/cloudtty/cloudshell:v0.3.0 # FROM the existing image 
COPY install-ttyd.sh /bin/install-ttyd.sh
COPY install-vela.sh /bin/install-vela.sh
RUN /bin/install-ttyd.sh && /bin/install-vela.sh
```

**Comment by barnettZQG** [comment]
> @barnettZQG
> 
> (1) **Use customized image** The team had discussed about the need of "customized runtime image" , because diff people want diff tools in image. so @calvin0327 has introduced the capability . When helm install cloudtty, add `--set jobTemplate.image.repository=kubevela/cloudshell ` to use your own image.
> 
> (2) **Build your own image** I take a quick look on your https://github.com/kubevela/cloudshell , I think you can do it by
> 
> ```
> FROM ghcr.io/cloudtty/cloudshell:v0.3.0 # FROM the existing image 
> COPY install-vela.sh /bin/install-vela.sh
> RUN  /bin/install-vela.sh
> ```

Yes. But need the cloudshell base image support arm64.

**Comment by barnettZQG** [comment]
This script support installing the arm64 ttyd.
https://github.com/kubevela/cloudshell/blob/main/install-ttyd.sh

**Comment by calvin0327** [comment]
https://github.com/cloudtty/cloudtty/runs/8168461848?check_suite_focus=true
@barnettZQG Now operator and cloudshell images both support `ARM64` and you can be built on our base image. If there is any problem, can you give us your feedback, thanks
