### ISSUE TITLE
cloudshell create ingress The network is abnormal

### ISSUE THREAD

**Issue by harlee-x** [cloudtty/cloudtty#415]
- use version: cloudtty 0.7.2
- problem description：After the cloudshell is created successfully, the url cannot be accessed immediately，The access is normal after a period of time
- suggest:  pod successfully created, then created ingress

![image](https://github.com/cloudtty/cloudtty/assets/23731971/b45ee725-72fc-4635-89ea-2c6620f1dfe5)

**Comment by calvin0327** [comment]
@harlee-x Did you use ingress mode?  It may take some time to update the route, I'm not sure.

**Comment by harlee-x** [comment]
yes, use ingress mode, It takes a while to see ingress provide support from use
