### ISSUE TITLE
cloudshell pod not delete

### ISSUE THREAD

**Issue by harlee-x** [cloudtty/cloudtty#416]
version: 0.7.2
problem: when commandAction use "kubectl exec xxx" to container, cloushell delete but pod is exists

**Comment by calvin0327** [comment]
@harlee-x Yes, the pod  is reusable, it don't have to delete and create pod repeatedly.

**Comment by harlee-x** [comment]
When the ttl time is up, the pod still cannot be deleted。
Ideally, the pod should be deleted after the ttl time is up no matter what the operation is, right

**Comment by calvin0327** [comment]
@harlee-x now, the ttl is time up, the pod is back up to the pool, if there are other cloudshell the pod will binding to the other cloudshell.

The purpose of doing this is to accelerate the startup speed of the cloudshell window.
