### ISSUE TITLE
Image pull failed for versions v0.6.3 >=

### ISSUE THREAD

**Issue by Michael-Xing** [cloudtty/cloudtty#444]
 docker pull ghcr.io/cloudtty/cloudshell:v0.6.3
Error response from daemon: Head "https://ghcr.io/v2/cloudtty/cloudshell/manifests/v0.6.3": Get "https://ghcr.io/token?scope=repository%3Acloudtty%2Fcloudshell%3Apull&service=ghcr.io": EOF

**Comment by yankay** [comment]
HI @Michael-Xing 

It's an issue of ghcr.io :-)
