### ISSUE TITLE
worker pod 资源泄露

### ISSUE THREAD

**Issue by haijianyang** [cloudtty/cloudtty#483]
## 问题描述
maxWorkerLimit 设置为 5，但是长期观察发现，worker pod 数量会一直大于 5。

```bash
# kubectl get pod 返回所有的 worker pod
NAME                           READY   STATUS    RESTARTS       AGE
cloudshell-worker-267vk7bpbt   1/1     Running   0              14h
cloudshell-worker-52hbbnlwlb   1/1     Running   0              14h
cloudshell-worker-dkzqt6fd4s   1/1     Running   0              14h
cloudshell-worker-g9zdb8qrhv   1/1     Running   0              14h
cloudshell-worker-zbhjnzcfvt   1/1     Running   0              21h
# cloudshell: demo-node-uopfwl
cloudshell-worker-jmzl5nsrp4   1/1     Running   0              21h
# cloudshell: demo-node-hm4rhd
cloudshell-worker-gcxpqvfh98   1/1     Running   0              22h
```

此时没有 CloudShell 对象，也就是 demo-node-uopfwl 和 demo-node-hm4rhd 其实已经被删除很长时间了。
```bash
# kubectl get cloudshell
No resources found in default namespace.

# kubectl get cloudshell -A
No resources found
```

同时也发现空闲的 worker pod 数量小于 5。
```bash
# kubectl get pods -l 'worker.cloudtty.io/owner-name=' 返回所有空闲的的 worker pod
NAME                           READY   STATUS    RESTARTS   AGE
cloudshell-worker-267vk7bpbt   1/1     Running   0          14h
cloudshell-worker-dkzqt6fd4s   1/1     Running   0          14h
cloudshell-worker-g9zdb8qrhv   1/1     Running   0          14h
cloudshell-worker-zbhjnzcfvt   1/1     Running   0          21h
```

进一步，发现 cloudshell-worker-jmzl5nsrp4 和 cloudshell-worker-gcxpqvfh98 的 worker.cloudtty.io/owner-name 还关联着已经被删除了的 CloudShell。
```bash
# kubectl get pod cloudshell-worker-gcxpqvfh98 -oyaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-09-26T07:52:14Z"
  labels:
    worker.cloudtty.io/binding-count: "7"
    worker.cloudtty.io/name: cloudshell-worker-gcxpqvfh98
    worker.cloudtty.io/owner-name: demo-node-hm4rhd
  name: cloudshell-worker-gcxpqvfh98
  namespace: default
```

因此判断 worker pod （cloudshell-worker-jmzl5nsrp4 和 cloudshell-worker-gcxpqvfh98）出现了泄露，出现泄露的 worker pod 不会被 worker pool 使用。

## 期望
CloudShell 被删除后，关联的 worker pod 应该进入 worker pool 被继续使用。

**Comment by calvin0327** [comment]
@flpanbin /cc

**Comment by wangxinghao** [comment]
在使用kubectl-node_shell时，也有这种情况，cloudshell关闭时，pod仍然存活。期望cloudshell为comleted状态时，能把对应的pod清理掉。

**Comment by flpanbin** [comment]
> 在使用kubectl-node_shell时，也有这种情况，cloudshell关闭时，pod仍然存活。期望cloudshell为comleted状态时，能把对应的pod清理掉。

为了提高控制台打开的速度，cloudshell 会复用已创建的 worker， 所以 worker 使用完后可能不会立即删除。如果空闲 worker 数不超过 core-worker-limit，则会一直保留。core-worker-limit 参数默认值为 5，麻烦确认下是否是这种场景。

如果不是上述场景麻烦描述下具体的操作步骤。

方便的话，麻烦贴下 cloudtty-controller-manager 的日志。

**Comment by wangxinghao** [comment]
0.5.0版本不会根据core-worker-limit进行复用，建议使用哪个版本？

**Comment by flpanbin** [comment]
> 0.5.0版本不会根据core-worker-limit进行复用，建议使用哪个版本？

使用新版本试试 0.7.8。

**Comment by wangxinghao** [comment]
有没有微信交流群，我的v：wangxinghao842434
