### ISSUE TITLE
ScaleInQueueDuration 支持配置

### ISSUE THREAD

**Issue by haijianyang** [cloudtty/cloudtty#484]
## 需求描述
当前 scaleInQueueDuration 使用的是代码默认的 `DefaultScaleInWorkerQueueDuration = time.Hour * 3`。
3h 对于要求快速回收 worker pod 资源的场景来说时间过于太久。

如果 scaleInQueueDuration 可以和 coreWorkerLimit, maxWorkerLimit 一样提供参数化配置即可满足个性化需求。

**Comment by calvin0327** [comment]
@haijianyang 这个提议非常好，你有兴趣贡献这个这个功能吗？
