### ISSUE TITLE
Support contextual logging

### ISSUE THREAD

**Issue by haijianyang** [cloudtty/cloudtty#485]
## 需求描述

当前项目中直接使用 klog 记录日志，日志没有详细的上下文信息（例如是哪个 cloudshell 或者 worker），导致排查问题不够明确和清晰。

例如下述的日志，没有说明是哪个 cloudshell 和 worker 报错：
```log
E0927 10:03:16.498026       1 cloudshell_controller.go:954] "failed to run command" err="command terminated with exit code 123" command=["/usr/lib/ttyd/reset.sh"]
E0927 10:03:16.498068       1 cloudshell_controller.go:732] "failed reset worker" err="command terminated with exit code 123"
```

可以参考社区日志的规范：[contextual logging](https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/3077-contextual-logging)

**Comment by flpanbin** [comment]
感谢您的反馈，这个问题我们排期优化下，也欢迎大家一起参与贡献。
