### ISSUE TITLE
feat: Implement basic auth feature for individual usage or integration with authantication provider 

### ISSUE THREAD

**Issue by wdcs-meetsoni** [cloudtty/cloudtty#489]
Implement basic auth feature for individual usage or integration with authentication provider through values.yaml 
authentication provider like keyclaok, casdoor etc.

**Comment by flpanbin** [comment]
Thanks for your feedback. We still need to think about and evaluate the authentication of cloudtty. If you have a specific plan, feel free to discuss and share it.
