### ISSUE TITLE
cloudtty终端web访问是否有相关鉴权？

### ISSUE THREAD

**Issue by pwddd** [cloudtty/cloudtty#490]
开发者你好，我想咨询一下是否有方式给通过NodePort方式开放的web终端增加鉴权？目前可以通过节点+端口直接访问终端，存在一定的安全风险。请问是否存在相关的功能实现鉴权？如果没有，是否有其他的缓解方案呢？目前ttyd支持通过-H方式进行鉴权的，cloudtty是否有相关的考虑？

**Comment by flpanbin** [comment]
目前没有直接在 cloudtty 做鉴权，鉴权逻辑需要使用方处理，cloudtty 除了 NodePort 还支持其他模式，比如可以通过 ingress 或 VirtualService 的方式将 cloudshell 路由到自身鉴权模块来实现鉴权。ttyd -H 支持添加 HTTP Header, 所以应该是只支持 k8s token 的方式鉴权，常用的证书方式可能不支持，这个我们需要再考虑评估下。如果有其他的方案欢迎讨论。
