### ISSUE TITLE
Permission control for cloud shell

### ISSUE THREAD

**Issue by jms820** [cloudtty/cloudtty#498]
Do we support namespace-level access control? Currently, after starting according to the example, full cluster permissions are granted. Is it possible to support access control to resources within a specific namespace without modifying the kubeconfig configuration?

**Comment by flpanbin** [comment]
Cloudshell access permissions are governed by the kubeconfig file. By utilizing distinct kubeconfig permission settings, you can grant varying levels of access to Cloudshell.
