### ISSUE TITLE
Shoud we use the github container registry

### ISSUE THREAD

**Issue by yankay** [cloudtty/cloudtty#5]
Shoud we use the github container registry as a OSS project: ghcr.io

https://github.com/cloudtty/cloudtty/blob/74e167f457dac6a751d2cdbdaeef0a9f665ccc4d/Makefile#L2

**Comment by panpan0000** [comment]
will do it soon.

**Comment by panpan0000** [comment]
Tasks:
 - change image repo to ghcr.io https://github.com/cloudtty/cloudtty/commit/88f9ffd1a18df4d2160732bc94fad57d467c0b28
 - change helm repo to ghcr.io ToDo

**Comment by panpan0000** [comment]
still struggle with https://github.com/cloudtty/cloudtty/blob/main/.github/workflows/helm-release.yaml
ghcr.io does not officially support helm repo, but with gh-pages workaround, and gh-pages has not be enabled so far..

**Comment by panpan0000** [comment]
still struggle with https://github.com/cloudtty/cloudtty/blob/main/.github/workflows/helm-release.yaml
ghcr.io does not officially support helm repo, but with gh-pages workaround, and gh-pages has not be enabled so far..

**Comment by panpan0000** [comment]
tracked helm chart with https://github.com/cloudtty/cloudtty/issues/28
