### ISSUE TITLE
Whether it can support the installation of plugins, such as karmadactl, etc.

### ISSUE THREAD

**Issue by zgfh** [cloudtty/cloudtty#63]
Whether it can support the installation of plugins, such as karmadactl, etc.
and the same user can continue to use their own environment next time

**Comment by panpan0000** [comment]
At my best guess, kubectl plugin may be more suitable?

**Comment by zgfh** [comment]
I me,like gce shell, favorite tools pre-installed and up to date
 ,and you can install others: https://cloud.google.com/shell?hl=zh-cn

**Comment by panpan0000** [comment]
this will be another feature :  customized image by @calvin0327 .
you can install any tool and build your own image, and cloudtty will use that image .

**Comment by calvin0327** [comment]
@zgfh done, we have buit-in `etcdctl` and `karmadactl` base tools. in order to control image size, user can build themself image base on cloudshell image.
