### ISSUE TITLE
The input window is too small

### ISSUE THREAD

**Issue by barnettZQG** [cloudtty/cloudtty#75]
![image](https://user-images.githubusercontent.com/18493394/179882362-dc561529-eaa8-4ed3-b56b-d2d9d8715846.png)

Hi, we build an [addon](https://github.com/kubevela/catalog/tree/master/addons/cloudshell) for [KubeVela](https://kubevela.net/) based on this project and provides the CloudShell feature.

A very experience-impairing problem here is that the input window is too small, as the picture shows.

**Comment by panpan0000** [comment]
@youhonglian  can you please take a look?

**Comment by kebe7jun** [comment]
same problem, the width of the terminal is too small, which causes me to be truncated even when typing commands.

![image](https://user-images.githubusercontent.com/7303612/181148695-43871682-5f96-4eb5-8585-2da3b058b34c.png)

**Comment by calvin0327** [comment]
@barnettZQG @kebe7jun Thank you for your feedback, we will release a version of V0.3.0 to fix these issues.

**Comment by barnettZQG** [comment]
@calvin0327  Great! when do you release the new version?

**Comment by calvin0327** [comment]
@barnettZQG We have a few more PR in the works and will probably release a new version within the next week.

**Comment by calvin0327** [comment]
https://github.com/cloudtty/cloudtty/releases/tag/v0.3.0

@barnettZQG the new version `v0.3.0` had released. welcome to try

**Comment by barnettZQG** [comment]
This issue is already fixed.

**Comment by calvin0327** [comment]
@barnettZQG we have released `v0.4.0` version, welcome to use, if have any questions, please feedback to us, thanks. 😄
