### ISSUE TITLE
Do we need to guard the cloudtty job?

### ISSUE THREAD

**Issue by barnettZQG** [cloudtty/cloudtty#94]
After the cloud shell instance is ready, I removed the job to mock exception. 

![image](https://user-images.githubusercontent.com/18493394/184275114-a1754f2c-7a55-4eb1-98fa-3f11a1baca9a.png)

The cloud shell status does not correctly reflect the true state.

**Comment by calvin0327** [comment]
@barnettZQG thanks for your feedback.
