### ISSUE TITLE
Idea: Support kubectl-node-shell

### ISSUE THREAD

**Issue by yankay** [cloudtty/cloudtty#99]
[kubectl node-shell](https://github.com/kvaps/kubectl-node-shell)  can use the node from shell.
It's useful and dangerous

**Comment by yankay** [comment]
I thinks it's too dangerous

**Comment by panpan0000** [comment]
![image](https://user-images.githubusercontent.com/14049268/185586929-0954c88b-144b-401f-8b8d-fd70cc7a92f7.png)

**Comment by panpan0000** [comment]
support it is easy, just install the binary into the base image.
But it's not open source and always pull image from internet. seems it's not well designed.

**Comment by yankay** [comment]
> support it is easy, just install the binary into the base image. But it's not open source and always pull image from internet. seems it's not well designed.

It can be configured https://github.com/kvaps/kubectl-node-shell/blob/master/kubectl-node_shell#L92
